Ext.data.JsonP.java_util_concurrent_CompletionException({"tagname":"class","name":"java.util.concurrent.CompletionException","autodetected":{},"files":[{"filename":"CompletionException.js","href":"CompletionException.html#java-util-concurrent-CompletionException"}],"extends":"java.lang.RuntimeException","since":"1.8","author":[{"tagname":"author","name":"Doug Lea","email":null}],"members":[],"alternateClassNames":[],"aliases":{},"id":"class-java.util.concurrent.CompletionException","classIcon":"icon-class","superclasses":["java.lang.RuntimeException"],"subclasses":[],"mixedInto":[],"mixins":[],"parentMixins":[],"requires":[],"uses":[],"html":"<div><pre class=\"hierarchy\"><h4>Hierarchy</h4><div class='subclass first-child'>java.lang.RuntimeException<div class='subclass '><strong>java.util.concurrent.CompletionException</strong></div></div><h4>Files</h4><div class='dependency'><a href='source/CompletionException.html#java-util-concurrent-CompletionException' target='_blank'>CompletionException.js</a></div></pre><div class='doc-contents'><p>Exception thrown when an error or other exception is encountered\n in the course of completing a result or task.</p>\n        <p>Available since: <b>1.8</b></p>\n</div><div class='members'></div></div>","meta":{}});