<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>The source code</title>
  <link href="../resources/prettify/prettify.css" type="text/css" rel="stylesheet" />
  <script type="text/javascript" src="../resources/prettify/prettify.js"></script>
  <style type="text/css">
    .highlight { display: block; background-color: #ddd; }
  </style>
  <script type="text/javascript">
    function highlight() {
      document.getElementById(location.hash.replace(/#/, "")).className = "highlight";
    }
  </script>
</head>
<body onload="prettyPrint(); highlight();">
  <pre class="prettyprint lang-js"><span id='java-util-concurrent-ExecutionException'>/**@class java.util.concurrent.ExecutionException
</span>@extends java.lang.Exception

 Exception thrown when attempting to retrieve the result of a task
 that aborted by throwing an exception. This exception can be
 inspected using the {@link #getCause}() method.

 @see Future
 @since 1.5
 @author Doug Lea
*/
var ExecutionException = {


};</pre>
</body>
</html>
