Ext.data.JsonP.java_security_cert_CertPathValidatorException({"tagname":"class","name":"java.security.cert.CertPathValidatorException","autodetected":{},"files":[{"filename":"CertPathValidatorException.js","href":"CertPathValidatorException.html#java-security-cert-CertPathValidatorException"}],"extends":"java.security.GeneralSecurityException","since":"1.4","author":[{"tagname":"author","name":"Yassir Elley","email":null}],"members":[{"name":"getCertPath","tagname":"method","owner":"java.security.cert.CertPathValidatorException","id":"method-getCertPath","meta":{}},{"name":"getIndex","tagname":"method","owner":"java.security.cert.CertPathValidatorException","id":"method-getIndex","meta":{}},{"name":"getReason","tagname":"method","owner":"java.security.cert.CertPathValidatorException","id":"method-getReason","meta":{}}],"alternateClassNames":[],"aliases":{},"id":"class-java.security.cert.CertPathValidatorException","short_doc":"An exception indicating one of a variety of problems encountered when\n validating a certification path. ...","classIcon":"icon-class","superclasses":["java.security.GeneralSecurityException"],"subclasses":[],"mixedInto":[],"mixins":[],"parentMixins":[],"requires":[],"uses":[],"html":"<div><pre class=\"hierarchy\"><h4>Hierarchy</h4><div class='subclass first-child'>java.security.GeneralSecurityException<div class='subclass '><strong>java.security.cert.CertPathValidatorException</strong></div></div><h4>Files</h4><div class='dependency'><a href='source/CertPathValidatorException.html#java-security-cert-CertPathValidatorException' target='_blank'>CertPathValidatorException.js</a></div></pre><div class='doc-contents'><p>An exception indicating one of a variety of problems encountered when\n validating a certification path.\n <p>\n A {@code CertPathValidatorException} provides support for wrapping\n exceptions. The getCause method returns the throwable,\n if any, that caused this exception to be thrown.\n <p>\n A {@code CertPathValidatorException} may also include the\n certification path that was being validated when the exception was thrown,\n the index of the certificate in the certification path that caused the\n exception to be thrown, and the reason that caused the failure. Use the\n <a href=\"#!/api/java.security.cert.CertPathValidatorException-method-getCertPath\" rel=\"java.security.cert.CertPathValidatorException-method-getCertPath\" class=\"docClass\">getCertPath</a>, <a href=\"#!/api/java.security.cert.CertPathValidatorException-method-getIndex\" rel=\"java.security.cert.CertPathValidatorException-method-getIndex\" class=\"docClass\">getIndex</a>, and\n <a href=\"#!/api/java.security.cert.CertPathValidatorException-method-getReason\" rel=\"java.security.cert.CertPathValidatorException-method-getReason\" class=\"docClass\">getReason</a> methods to retrieve this information.</p>\n\n<p> <p>\n <b>Concurrent Access</b>\n <p>\n Unless otherwise specified, the methods defined in this class are not\n thread-safe. Multiple threads that need to access a single\n object concurrently should synchronize amongst themselves and\n provide the necessary locking. Multiple threads each manipulating\n separate objects need not synchronize.</p>\n\n<p> @see CertPathValidator</p>\n        <p>Available since: <b>1.4</b></p>\n</div><div class='members'><div class='members-section'><div class='definedBy'>Defined By</div><h3 class='members-title icon-method'>Methods</h3><div class='subsection'><div id='method-getCertPath' class='member first-child not-inherited'><a href='#' class='side expandable'><span>&nbsp;</span></a><div class='title'><div class='meta'><span class='defined-in' rel='java.security.cert.CertPathValidatorException'>java.security.cert.CertPathValidatorException</span><br/><a href='source/CertPathValidatorException.html#java-security-cert-CertPathValidatorException-method-getCertPath' target='_blank' class='view-source'>view source</a></div><a href='#!/api/java.security.cert.CertPathValidatorException-method-getCertPath' class='name expandable'>getCertPath</a>( <span class='pre'></span> ) : Object {java.security.cert.CertPath}<span class=\"signature\"></span></div><div class='description'><div class='short'>Returns the certification path that was being validated when\n the exception was thrown. ...</div><div class='long'><p>Returns the certification path that was being validated when\n the exception was thrown.</p>\n<h3 class='pa'>Returns</h3><ul><li><span class='pre'>Object {java.security.cert.CertPath}</span><div class='sub-desc'><p>the {@code CertPath} that was being validated when\n the exception was thrown (or {@code null} if not specified)</p>\n</div></li></ul></div></div></div><div id='method-getIndex' class='member  not-inherited'><a href='#' class='side expandable'><span>&nbsp;</span></a><div class='title'><div class='meta'><span class='defined-in' rel='java.security.cert.CertPathValidatorException'>java.security.cert.CertPathValidatorException</span><br/><a href='source/CertPathValidatorException.html#java-security-cert-CertPathValidatorException-method-getIndex' target='_blank' class='view-source'>view source</a></div><a href='#!/api/java.security.cert.CertPathValidatorException-method-getIndex' class='name expandable'>getIndex</a>( <span class='pre'></span> ) : Number<span class=\"signature\"></span></div><div class='description'><div class='short'>Returns the index of the certificate in the certification path\n that caused the exception to be thrown. ...</div><div class='long'><p>Returns the index of the certificate in the certification path\n that caused the exception to be thrown. Note that the list of\n certificates in a {@code CertPath} is zero based. If no\n index has been set, -1 is returned.</p>\n<h3 class='pa'>Returns</h3><ul><li><span class='pre'>Number</span><div class='sub-desc'><p>the index that has been set, or -1 if none has been set</p>\n</div></li></ul></div></div></div><div id='method-getReason' class='member  not-inherited'><a href='#' class='side expandable'><span>&nbsp;</span></a><div class='title'><div class='meta'><span class='defined-in' rel='java.security.cert.CertPathValidatorException'>java.security.cert.CertPathValidatorException</span><br/><a href='source/CertPathValidatorException.html#java-security-cert-CertPathValidatorException-method-getReason' target='_blank' class='view-source'>view source</a></div><a href='#!/api/java.security.cert.CertPathValidatorException-method-getReason' class='name expandable'>getReason</a>( <span class='pre'></span> ) : Object {java.security.cert.CertPathValidatorException.Reason}<span class=\"signature\"></span></div><div class='description'><div class='short'>Returns the reason that the validation failed. ...</div><div class='long'><p>Returns the reason that the validation failed. The reason is\n associated with the index of the certificate returned by\n <a href=\"#!/api/java.security.cert.CertPathValidatorException-method-getIndex\" rel=\"java.security.cert.CertPathValidatorException-method-getIndex\" class=\"docClass\">getIndex</a>.</p>\n        <p>Available since: <b>1.7</b></p>\n<h3 class='pa'>Returns</h3><ul><li><span class='pre'>Object {java.security.cert.CertPathValidatorException.Reason}</span><div class='sub-desc'><p>the reason that the validation failed, or\n    {@code BasicReason.UNSPECIFIED} if a reason has not been\n    specified</p>\n</div></li></ul></div></div></div></div></div></div></div>","meta":{}});